services:
  postgresdb:
    image: postgres:14
    container_name: talentboard-postgres
    environment:
      POSTGRES_DB: talentboard_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  springbootapp:
    build: .
    container_name: talentboard-api
    ports:
      - "8081:8081"
    depends_on:
      - postgresdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/talentboard_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: securepassword123
      APP_JWT_SECRET: MiClaveSuperSecretaYSeguraParaTalentBoard2026!

volumes:
  pgdata: