spring.application.name=talentboard

# Configuración de Conexión a PostgreSQL (Cambia las credenciales según tu entorno)
spring.datasource.url=jdbc:postgresql://localhost:5432/talentboard_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Propiedades de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PROPIEDAD PERSONALIZADA: Clave JWT fija (Mínimo de 256 bits/32 caracteres en texto plano para HS256)
app.jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUVG9rZW5zMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=